# Generated by Django 2.2.5 on 2020-01-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='bet',
            new_name='team_bet',
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
