# Generated by Django 2.2.5 on 2019-12-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notdolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notdoitem',
            name='notdo_description',
            field=models.CharField(default='Put reasons here.', max_length=200),
        ),
    ]
