# Generated by Django 2.2.5 on 2019-12-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('text', models.CharField(default='What have you done?', max_length=400)),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='When')),
                ('counts', models.IntegerField(default=0, help_text='It happens for how many times?')),
            ],
        ),
    ]
