# Generated by Django 2.2.5 on 2019-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, unique=True)),
                ('teamA_bet', models.IntegerField(default=0)),
                ('teamB_bet', models.IntegerField(default=0)),
            ],
        ),
    ]
