# Generated by Django 2.2.5 on 2019-12-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
