# Generated by Django 2.2.5 on 2019-12-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1205', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='todo_description',
            field=models.CharField(default='Reason for todo', max_length=200),
        ),
    ]
