# Generated by Django 2.2.5 on 2020-01-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls0120', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
