# Generated by Django 2.2.5 on 2019-12-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event1210', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
