# Generated by Django 2.2.5 on 2020-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event1210', '0003_choice_choice_odd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_odd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
