# Generated by Django 2.2.5 on 2020-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event0123', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_bet',
            field=models.IntegerField(default=0),
        ),
    ]
