# Generated by Django 2.2.5 on 2020-01-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event0123', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_bet_history',
            field=models.TextField(default=''),
        ),
    ]
