# Generated by Django 2.2.5 on 2020-01-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_solution',
            field=models.CharField(default='', max_length=400),
        ),
    ]
