# Generated by Django 2.2.5 on 2020-01-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0002_event_event_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
