# Generated by Django 2.2.5 on 2019-12-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_point',
            field=models.IntegerField(default=0),
        ),
    ]
